name: Generate Snake Animation

on:
  schedule:
    # Runs every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          # The output file name. Defaults to 'github-contribution-grid-snake.svg'
          
          # For dark mode:
          outputs: dist/github-contribution-grid-snake-dark.svg?palette=github-dark
